name: "Hello World Workflow"

on:
  push:
    branches:
      - master
      - production
  
  # trigger the workflow on push to master or production branches

  jobs:
    hello_world_job:
      runs-on: ubuntu-latest

      steps:
        - name: "Print Hello World"
          run: echo "Hello, World!"
        - name: "Print Current Date and Time"
          run: date